### ISSUE TITLE
Более деликатная проверка на SyntaxError

### ISSUE THREAD

**Issue by Kuznetsov-Ilia** [Kureev/browserify-patch-server#2]
Привет! Спасибо что пинаешь столь интересную тему в столь застойное время)
https://github.com/Kureev/browserify-patch-server/blob/master/index.js#L107 тут у меня всегда беда, 'SyntaxError' встречается и в комментах и в сборщике ошибок.... Возможен ли другой вариант выявления ошибки?

**Comment by Kureev** [comment]
Привет! Мне тоже не нравится подобный подход к обработке ошибок на этапе компиляции, но увы, если что-то идет не так, текст ошибки пишется в файл вместо контента (поведение browserify) и в данный момент я не знаю, как ещё можно с этим работать. 

P.S. Лучше все-таки на английском :)
